*Topic*: Data Science  
*Author*: Luz Enseñat de Carlos

# Movie and User Ratings Data Processing

We will use Pandas to manage and transform the data.

In [47]:
import pandas as pd

## We will work with a dataset containing information about movies and user ratings.

The file *movies.csv* contains the following columns:

* **movieId**: movie identifier.
* **title**: movie title.
* **genres**: movie genres. They are separated by the "|" character.

The file *ratings.csv* contains the following columns:

* **userId**: identifier of the user who rated the movie.
* **movieId**: movie identifier.
* **rating**: movie rating given by the user, on a scale from 0.5 to 5.
* **timestamp**: date and time when the rating was made. It is stored in UNIX format, meaning the number of seconds elapsed since January 1, 1970. Later, we will see how to convert it into a more readable format.

### 1. Data Loading

We read the data files and store them in two Pandas DataFrames called `movies` and `ratings`.

In [48]:
# We read the movie and ratings files and store them in two DataFrames:

movies = pd.read_csv("https://raw.githubusercontent.com/Luz-Ensenat/movie-ratings-data-analysis/main/data/movies.csv")

ratings = pd.read_csv("https://raw.githubusercontent.com/Luz-Ensenat/movie-ratings-data-analysis/main/data/ratings.csv")

# We inspect the size of each DataFrame to know the number of movies and ratings:

print(f"Number of movies in the movies DataFrame: {movies.shape[0]}")
print(f"Number of ratings in the ratings DataFrame: {ratings.shape[0]}")

# We inspect the columns contained in each DataFrame:

print(f"The columns in the movies DataFrame are: {movies.columns}")
print(f"The columns in the ratings DataFrame are: {ratings.columns}")

Number of movies in the movies DataFrame: 45447
Number of ratings in the ratings DataFrame: 500000
The columns in the movies DataFrame are: Index(['movieId', 'title', 'genres'], dtype='object')
The columns in the ratings DataFrame are: Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

### 2. DataFrame Merge

We add the movie titles and genres to the ratings table so that we have a single table containing all the information. We will call it `movie_ratings`.

Movies without ratings or ratings for unknown movies are not relevant for our analysis.

In [49]:
# We merge the two DataFrames using movieId as the common column and apply a left join:

movie_ratings = ratings.merge(movies[['movieId', 'title', 'genres']], on='movieId', how='left')

# We inspect the resulting final DataFrame:

movie_ratings

,userId,movieId,rating,timestamp,title,genres
0,1,110,1.0,1425941529,Braveheart (1995),Action|Drama|War
1,1,147,4.5,1425942435,"Basketball Diaries, The (1995)",Drama
2,1,858,5.0,1425941523,"Godfather, The (1972)",Crime|Drama
3,1,1221,5.0,1425941546,"Godfather: Part II, The (1974)",Crime|Drama
4,1,1246,5.0,1425941556,Dead Poets Society (1989),Drama
...,...,...,...,...,...,...
499995,5178,313,3.0,951441004,"Swan Princess, The (1994)",Animation|Children
499996,5178,551,4.0,951441689,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
499997,5178,588,4.0,951441938,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
499998,5178,594,3.0,951442024,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
499999,5178,595,3.0,951441837,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX

### 3. Example: calculation of the ratings received by the movie "Dark Knight, The (2008)" and how many of them are 5-star ratings

In [50]:
# We filter the ratings for the movie "Dark Knight, The (2008)" and display the resulting DataFrame:

dk_ratings = movie_ratings[movie_ratings['title'] == 'Dark Knight, The (2008)']

dk_ratings

,userId,movieId,rating,timestamp,title,genres
14,1,58559,4.0,1425942007,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
183,7,58559,5.0,1486253675,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
612,11,58559,4.5,1231675382,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1094,15,58559,5.0,1346002472,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1534,20,58559,5.0,1367493748,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
...,...,...,...,...,...,...
497044,5146,58559,4.0,1391768244,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
498262,5158,58559,3.5,1420022656,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
498716,5163,58559,2.5,1375044030,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
499010,5169,58559,5.0,1265502221,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
499958,5177,58559,4.0,1492381890,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX

In [51]:
# We calculate the total number of ratings and print the result:

total_ratings_dk = dk_ratings.shape[0]

print("Total number of ratings for the movie Dark Knight, The (2008):", total_ratings_dk)

Total number of ratings for the movie Dark Knight, The (2008): 794

In [52]:
# We apply a double filter to the movie "Dark Knight, The (2008)", keeping only 5-star ratings, and display the resulting DataFrame:

dk_ratings_5 = movie_ratings[(movie_ratings['title'] == 'Dark Knight, The (2008)') & (movie_ratings['rating'] == 5.0)]

dk_ratings_5

,userId,movieId,rating,timestamp,title,genres
183,7,58559,5.0,1486253675,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1094,15,58559,5.0,1346002472,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1534,20,58559,5.0,1367493748,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11787,136,58559,5.0,1427637551,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
12020,146,58559,5.0,1423159909,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
...,...,...,...,...,...,...
494330,5119,58559,5.0,1450393218,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
496236,5139,58559,5.0,1268936878,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
496296,5140,58559,5.0,1496628412,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
496386,5141,58559,5.0,1433487698,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
499010,5169,58559,5.0,1265502221,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX

In [53]:
# We calculate the total number of 5-star ratings and print the result:

ratings_5_dk = dk_ratings_5.shape[0]

print("Total number of 5-star ratings for the movie Dark Knight, The (2008):", ratings_5_dk)

Total number of 5-star ratings for the movie Dark Knight, The (2008): 240

### 4. Calculation of the average rating and the number of ratings for each movie

We store the result in a new DataFrame called `movie_stats`.

In [54]:
# We create the movie_stats DataFrame by grouping movies by title using groupby and calculating the average rating and number of ratings using mean and size:

movie_stats = movie_ratings.groupby('title').agg(
    rating_count=('rating', 'size'),
    rating_mean=('rating', 'mean')
).reset_index()

movie_stats

,title,rating_count,rating_mean
0,"""Great Performances"" Cats (1998)",3,2.666667
1,#Horror (2015),1,2.500000
2,$ (Dollars) (1971),1,2.500000
3,$5 a Day (2008),1,2.500000
4,$9.99 (2008),2,3.500000
...,...,...,...
15467,À propos de Nice (1930),1,4.500000
15468,Ο Θανάσης στη χώρα της σφαλιάρας (1976),1,4.500000
15469,Каменная башка (2008),1,4.000000
15470,‘Rameau’s Nephew’ by Diderot (Thanx to Dennis ...,1,4.000000
15471,貞子3D (2012),1,1.000000

### 5. Calculation of the movie with the highest average rating

To obtain a more reliable result, we filter movies with at least 100 ratings and extract the top 10 movies with the highest average rating.

In [55]:
# We filter movies with at least 100 ratings:

filtered_stats = movie_stats[movie_stats['rating_count'] >= 100]

# We sort by average rating in descending order using sort_values and extract the top 10 using head:

top_10_movies = filtered_stats.sort_values(by='rating_mean', ascending=False).head(10)

top_10_movies

                                             title  rating_count  rating_mean
11985             Shawshank Redemption, The (1994)          1837     4.421611
14167     Treasure of the Sierra Madre, The (1948)           113     4.371681
3997                       Double Indemnity (1944)           109     4.366972
5516                         Godfather, The (1972)          1161     4.361326
14520                   Usual Suspects, The (1995)          1196     4.309783
11883  Seven Samurai (Shichinin no samurai) (1954)           259     4.283784
11036                           Rear Window (1954)           405     4.279012
9963        One Flew Over the Cuckoo's Nest (1975)           793     4.274905
13826                        Third Man, The (1949)           131     4.270992
1665                         Big Sleep, The (1946)           110     4.268182

### 6. Extraction of the movie release year

The movie release year appears in parentheses in the title. We will add a column to the `movies` DataFrame containing the movie year, assuming it is always located in the same position.

We will use a lambda function to extract the year from the title. Once extracted, we will remove the year from the title.

In [56]:
# We import the re module to search for the year within movie titles:

import re
import numpy as np

# We extract the year in parentheses if it exists (otherwise it would raise an error) and store it in a new column called 'year':

def extract_year(title):
    m = re.search(r'\((\d{4})\)', title)
    return m.group(1) if m else np.nan

movies['year'] = movies['title'].apply(extract_year)

movies

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji (1995),Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men (1995),Comedy|Romance,1995
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II (1995),Comedy,1995
...,...,...,...,...
45442,176267,Robin Hood (1991),Action|Drama|Romance,1991
45443,176271,Century of Birthing (2011),Drama,2011
45444,176273,Betrayal (2003),Action|Drama|Thriller,2003
45445,176275,Satan Triumphant (1917),(no genres listed),1917
45446,176279,Queerama (2017),(no genres listed),2017

In [57]:
# We remove the year and parentheses from the title using a lambda function:

movies['title'] = movies['title'].apply(lambda x: re.sub(r'\s*\(\d{4}\)', '', x))

movies

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995
...,...,...,...,...
45442,176267,Robin Hood,Action|Drama|Romance,1991
45443,176271,Century of Birthing,Drama,2011
45444,176273,Betrayal,Action|Drama|Thriller,2003
45445,176275,Satan Triumphant,(no genres listed),1917
45446,176279,Queerama,(no genres listed),2017

### 7. Genre Filtering

We will filter movies belonging to a specific genre. For example, we will obtain action movies released in 1993.

In [58]:
# First, we convert the "year" column to integer format. If conversion fails, the value is replaced with NaN (Not a Number) using coerce.
# We use loc to avoid the SettingWithCopyWarning error:

movies.loc[:, 'year'] = pd.to_numeric(movies['year'], errors='coerce')

# We filter Action movies released in 1993 using str.contains and display the result:

action_93 = movies[movies['genres'].str.contains('Action') & (movies['year'] == 1993)]

action_93

,movieId,title,genres,year
281,284,New York Cop (Nyû Yôku no koppu),Action|Crime,1993.0
430,434,Cliffhanger,Action|Adventure|Thriller,1993.0
438,442,Demolition Man,Action|Adventure|Sci-Fi,1993.0
460,464,Hard Target,Action|Adventure|Crime|Thriller,1993.0
461,465,Heaven & Earth,Action|Drama|War,1993.0
...,...,...,...,...
42832,169820,To Be the Best,Action,1993.0
44036,172621,"It's sunny on Deribassovskaya, or: It's rainin...",Action|Comedy|Crime,1993.0
44253,173117,Quest of the Delta Knights,Action|Adventure|Fantasy,1993.0
44359,173359,Sharpe's Rifles,Action|Adventure|War,1993.0
45410,176191,Fit to Kill,Action|Romance|Thriller,1993.0

### 8. UNIX Date Column Processing

The `timestamp` field in the `ratings` table is stored in UNIX format.

We will create a new column in the `ratings` DataFrame called `date` containing the date in a readable format.

We will also calculate when the first and last ratings were made.

In [59]:
# We create a new readable "date" column by converting the UNIX timestamp using Pandas to_datetime:

ratings['date'] = pd.to_datetime(ratings['timestamp'], unit='s')

ratings

        userId  movieId  rating   timestamp                date
0            1      110     1.0  1425941529 2015-03-09 22:52:09
1            1      147     4.5  1425942435 2015-03-09 23:07:15
2            1      858     5.0  1425941523 2015-03-09 22:52:03
3            1     1221     5.0  1425941546 2015-03-09 22:52:26
4            1     1246     5.0  1425941556 2015-03-09 22:52:36
...        ...      ...     ...         ...                 ...
499995    5178      313     3.0   951441004 2000-02-25 01:10:04
499996    5178      551     4.0   951441689 2000-02-25 01:21:29
499997    5178      588     4.0   951441938 2000-02-25 01:25:38
499998    5178      594     3.0   951442024 2000-02-25 01:27:04
499999    5178      595     3.0   951441837 2000-02-25 01:23:57

[500000 rows x 5 columns]

In [60]:
# We print the dates of the first and last ratings:

print("First rating:", ratings['date'].min())
print("Last rating:", ratings['date'].max())

First rating: 1996-03-27 17:20:36
Last rating: 2017-08-04 04:52:46