*Tema*: Data Science\
*Autora*: Luz Enseñat de Carlos

# Tratamiento de Datos de Películas y Valoraciones de Usuarios

Utilizaremos Pandas para manejar y transformar los datos

In [40]:
import pandas as pd

## Vamos a trabajar con un conjunto de datos que contiene información sobre películas y valoraciones de usuarios.

El fichero *movies.csv* contiene las siguientes columnas:
* **movieId**: identificador de la película.
* **title**: título de la película.
* **genres**: géneros de la película. Están separados por el carácter "|".

El fichero *ratings.csv* contiene las siguientes columnas:

* **userId**: identificador del usuario que ha valorado la película.
* **movieId**: identificador de la película.
* **rating**: valoración de la película por el usuario, en una escala de 0.5 a 5.
* **timestamp**: fecha y hora en la que se realizó la valoración. Está en formato UNIX, es decir, el número de segundos que han pasado desde el 1 de enero de 1970. Luego veremos cómo convertirlo a un formato más legible.

### 1. Carga de datos

Leemos los ficheros de datos y los almacenamos en dos DataFrames de Pandas. os llamamoss `movies` y `ratings`

In [41]:
# Leemos los ficheros de películas y valoraciones almacenándolos en dos DataFrames:

movies = pd.read_csv("https://raw.githubusercontent.com/Luz-Ensenat/movie-ratings-data-analysis/main/data/movies.csv")

ratings = pd.read_csv("https://raw.githubusercontent.com/Luz-Ensenat/movie-ratings-data-analysis/main/data/ratings.csv")

# Vemos los tamaños que tiene cada uno para saber el nº de películas y de valoraciones:

print (f"Nº de películas en el DataFrame movies: {movies.shape[0]}")
print (f"Nº de Valoraciones en el DataFrame ratings: {ratings.shape[0]}")

# Vemos las columnas que contine cada DataFrame:

print (f"Las columnas del DataFrame movies son: {movies.columns}")
print (f"Las columnas del DataFrame ratings son: {ratings.columns}")

Nº de películas en el DataFrame movies: 45447
Nº de Valoraciones en el DataFrame ratings: 500000
Las columnas del DataFrame movies son: Index(['movieId', 'title', 'genres'], dtype='object')
Las columnas del DataFrame ratings son: Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

### 2. Union de DataFrames

Añadimos el título y los géneros de las películas a la tabla de valoraciones de tal forma que tengamos una única tabla con toda la información. La llamaremos `movie_ratings`. Las películas que no tengan valoraciones o ratings de películas que no conocemos no nos interesan.

In [42]:
# Unimos los dos DataFrames por movieId, la columna común para hacer la unión y teniendo en cuenta con inner sólo las que coincidan en ambos:

movie_ratings = ratings.merge(movies[['movieId', 'title', 'genres']], on='movieId', how='left')

# Vemos cómo ha quedado nuestro DataFrame final:

movie_ratings

,userId,movieId,rating,timestamp,title,genres
0,1,110,1.0,1425941529,Braveheart (1995),Action|Drama|War
1,1,147,4.5,1425942435,"Basketball Diaries, The (1995)",Drama
2,1,858,5.0,1425941523,"Godfather, The (1972)",Crime|Drama
3,1,1221,5.0,1425941546,"Godfather: Part II, The (1974)",Crime|Drama
4,1,1246,5.0,1425941556,Dead Poets Society (1989),Drama
...,...,...,...,...,...,...
499995,5178,313,3.0,951441004,"Swan Princess, The (1994)",Animation|Children
499996,5178,551,4.0,951441689,"Nightmare Before Christmas, The (1993)",Animation|Children|Fantasy|Musical
499997,5178,588,4.0,951441938,Aladdin (1992),Adventure|Animation|Children|Comedy|Musical
499998,5178,594,3.0,951442024,Snow White and the Seven Dwarfs (1937),Animation|Children|Drama|Fantasy|Musical
499999,5178,595,3.0,951441837,Beauty and the Beast (1991),Animation|Children|Fantasy|Musical|Romance|IMAX

### 3. Ejemoplo: cálculo de las valoraciones que ha recibido la película "Dark Knight, The (2008)" y cuántas de ellas son de 5 estrellas

In [43]:
# Filtramos las valoraciones de la película "Dark Knight, The (2008)" e imprimimos el DataFrame resultante:

dk_ratings = movie_ratings[movie_ratings['title'] == 'Dark Knight, The (2008)']

dk_ratings

,userId,movieId,rating,timestamp,title,genres
14,1,58559,4.0,1425942007,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
183,7,58559,5.0,1486253675,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
612,11,58559,4.5,1231675382,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1094,15,58559,5.0,1346002472,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1534,20,58559,5.0,1367493748,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
...,...,...,...,...,...,...
497044,5146,58559,4.0,1391768244,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
498262,5158,58559,3.5,1420022656,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
498716,5163,58559,2.5,1375044030,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
499010,5169,58559,5.0,1265502221,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
499958,5177,58559,4.0,1492381890,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX

In [44]:
# Medimos el número total de valoraciones y lo imprimimos:

total_valoraciones_dk = dk_ratings.shape[0]

print("Número total de valoraciones de la película Dark Knight, The (2008):", total_valoraciones_dk)

Número total de valoraciones de la película Dark Knight, The (2008): 794

In [45]:
# Realizamos un doble filtro sobre la película "Dark Knight, The (2008)", dejando sólo las valoraciones de 5 estrellas e imprimimos el DataFrame resultante:

dk_ratings_5 = movie_ratings[(movie_ratings['title'] == 'Dark Knight, The (2008)') & (movie_ratings['rating'] == 5.0)]

dk_ratings_5

,userId,movieId,rating,timestamp,title,genres
183,7,58559,5.0,1486253675,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1094,15,58559,5.0,1346002472,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
1534,20,58559,5.0,1367493748,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
11787,136,58559,5.0,1427637551,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
12020,146,58559,5.0,1423159909,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
...,...,...,...,...,...,...
494330,5119,58559,5.0,1450393218,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
496236,5139,58559,5.0,1268936878,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
496296,5140,58559,5.0,1496628412,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
496386,5141,58559,5.0,1433487698,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX
499010,5169,58559,5.0,1265502221,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX

In [46]:
# Medimos el número total de valoraciones 5 estrellas y lo imprimimos:

valoraciones_5_dk = dk_ratings_5.shape[0]

print("Total de valoraciones 5 estrellas de la película Dark Knight, The (2008):", valoraciones_5_dk)

Total de valoraciones 5 estrellas de la película Dark Knight, The (2008): 240

### 4. Cálculo de la valoracion media y el número de valoraciones de cada película

Almacenamos el resultado en un nuevo DataFrame llamado `movie_stats`.

In [47]:
# Creamos el DataFrame movie_stats grupando las películas por título mediante groupby y calculando la media y el número de valoraciones mediante mean y size:

movie_stats = movie_ratings.groupby('title').agg(rating_count = ('rating', 'size'), rating_mean = ('rating', 'mean')).reset_index()

movie_stats

,title,rating_count,rating_mean
0,"""Great Performances"" Cats (1998)",3,2.666667
1,#Horror (2015),1,2.500000
2,$ (Dollars) (1971),1,2.500000
3,$5 a Day (2008),1,2.500000
4,$9.99 (2008),2,3.500000
...,...,...,...
15467,À propos de Nice (1930),1,4.500000
15468,Ο Θανάσης στη χώρα της σφαλιάρας (1976),1,4.500000
15469,Каменная башка (2008),1,4.000000
15470,‘Rameau’s Nephew’ by Diderot (Thanx to Dennis ...,1,4.000000
15471,貞子3D (2012),1,1.000000

### 5. Cálculo de la película que tiene la valoración media más alta

Para tener un resutltado más fiable filtramos aquellas películas que tengan al menos 100 valoraciones y extraemos el top 10 de películas con la valoración media más alta.

In [48]:
# Filtramos películas con al menos 100 valoraciones:

filtered_stats = movie_stats[movie_stats['rating_count'] >= 100]

# Ordenamos por valoración media descendente mediante sort y extraemos el top 10 mediante head:

top_10_peliculas = filtered_stats.sort_values(by='rating_mean', ascending=False).head(10)

top_10_peliculas

                                             title  rating_count  rating_mean
11985             Shawshank Redemption, The (1994)          1837     4.421611
14167     Treasure of the Sierra Madre, The (1948)           113     4.371681
3997                       Double Indemnity (1944)           109     4.366972
5516                         Godfather, The (1972)          1161     4.361326
14520                   Usual Suspects, The (1995)          1196     4.309783
11883  Seven Samurai (Shichinin no samurai) (1954)           259     4.283784
11036                           Rear Window (1954)           405     4.279012
9963        One Flew Over the Cuckoo's Nest (1975)           793     4.274905
13826                        Third Man, The (1949)           131     4.270992
1665                         Big Sleep, The (1946)           110     4.268182

### 6. Extracción del año de la película

El año de la película se encuentra entre paréntesis en el título. Añadiremos una columna al DataFrame `movies` con el año de la película asumiendo que siempre se encuentra en la misma posición. Utilizaremos una función lambda para extraer el año del título. Una vez que lo hayamos extraído, eliminaremos el año del título.

In [49]:
# Importamos el módulo re para buscar el año dentro del título de las películas:

import re
import numpy as np

# Extraemos el año entre paréntesis si existe (porque si no existe nos da error) y lo guardamos en una nueva columna 'year':

def extrae_año(título):
    m = re.search(r' (\d4)', título)
    return m.group(1) if m else np.nan

movies['year'] = movies['title'].apply(extrae_año)

movies

,movieId,title,genres,year
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,NaN
1,2,Jumanji (1995),Adventure|Children|Fantasy,NaN
2,3,Grumpier Old Men (1995),Comedy|Romance,NaN
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,NaN
4,5,Father of the Bride Part II (1995),Comedy,NaN
...,...,...,...,...
45442,176267,Robin Hood (1991),Action|Drama|Romance,NaN
45443,176271,Century of Birthing (2011),Drama,NaN
45444,176273,Betrayal (2003),Action|Drama|Thriller,NaN
45445,176275,Satan Triumphant (1917),(no genres listed),NaN
45446,176279,Queerama (2017),(no genres listed),NaN

In [50]:
# Eliminamos el año y los paréntesis del título mediante una función lambda:

movies['title'] = movies['title'].apply(lambda x: re.sub(r'\s*\(\d{4}\)', '', x))

movies

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,NaN
1,2,Jumanji,Adventure|Children|Fantasy,NaN
2,3,Grumpier Old Men,Comedy|Romance,NaN
3,4,Waiting to Exhale,Comedy|Drama|Romance,NaN
4,5,Father of the Bride Part II,Comedy,NaN
...,...,...,...,...
45442,176267,Robin Hood,Action|Drama|Romance,NaN
45443,176271,Century of Birthing,Drama,NaN
45444,176273,Betrayal,Action|Drama|Thriller,NaN
45445,176275,Satan Triumphant,(no genres listed),NaN
45446,176279,Queerama,(no genres listed),NaN

### 7. Filtro por género

Filtraremos las películas de un género concreto. Por ejemplo, obtendremos las películas de acción de 1993.

In [51]:
# Primero convertimos a número entero la columna "year" y, si no parece, lo sustituimos por NaN (Not a Number) mediante coerce. Usamos loc para evitar el error SettingWithCopyWarning:

movies.loc[:, 'year'] = pd.to_numeric(movies['year'], errors='coerce')

# Filtramos las películas de acción (genres) de 1993 (year) mediante  el método str.contains e imprimimos:

action_93 = movies[movies['genres'].str.contains('Action') & (movies['year']==1993)]

action_93

Empty DataFrame
Columns: [movieId, title, genres, year]
Index: []

### 8. Tratamiento columna de fecha UNIX

El campo `timestamp` de la tabla `ratings` está en formato UNIX. Crearemos una nueva columna en la tabla `ratings` llamada `date` que contenga la fecha en un formato legible. Calcularemos cuándo fue la primera y la última valoración.

In [52]:
# Creamos una nueva columna "date" legible convirtiéndolo mediante to_datetime de Pandas:

ratings['date'] = pd.to_datetime(ratings['timestamp'], unit='s')

ratings

        userId  movieId  rating   timestamp                date
0            1      110     1.0  1425941529 2015-03-09 22:52:09
1            1      147     4.5  1425942435 2015-03-09 23:07:15
2            1      858     5.0  1425941523 2015-03-09 22:52:03
3            1     1221     5.0  1425941546 2015-03-09 22:52:26
4            1     1246     5.0  1425941556 2015-03-09 22:52:36
...        ...      ...     ...         ...                 ...
499995    5178      313     3.0   951441004 2000-02-25 01:10:04
499996    5178      551     4.0   951441689 2000-02-25 01:21:29
499997    5178      588     4.0   951441938 2000-02-25 01:25:38
499998    5178      594     3.0   951442024 2000-02-25 01:27:04
499999    5178      595     3.0   951441837 2000-02-25 01:23:57

[500000 rows x 5 columns]

In [53]:
# Imprimimos cuándo fué la primera y la última valoraciones:

print("Primera valoración:", ratings['date'].min())
print("Última valoración:",    ratings['date'].max())

Primera valoración: 1996-03-27 17:20:36
Última valoración: 2017-08-04 04:52:46